### ISSUE TITLE
Non-existant hostname/domain name routes to external ip

### ISSUE THREAD

**Issue by ashrude** [lo2dev/Echo#4]
![image](https://github.com/user-attachments/assets/dcfe2a81-4bad-4cf7-9ef8-02ca13de493a)

Interestingly enough, any invalid domains will fail.

![image](https://github.com/user-attachments/assets/8da5afab-4ec6-4db5-b2c7-342bfadeb927)

So I suspect this is a quirk with icmplib or dns itself.

**Comment by lo2dev** [comment]
`desgkrdhgbfhjd` doesn't work for me so it might be your network

![Screenshot from 2024-09-02 16-00-20](https://github.com/user-attachments/assets/093b6c7a-c995-4390-8fc3-98722c938952)

<details>
<summary>CLI icmplib output</summary>

```python
>>> from icmplib import ping
>>> host = ping('desgkrdhgbfhjd', count=4)
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.12/site-packages/icmplib/utils.py", line 108, in resolve
    lookup = socket.getaddrinfo(
             ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/socket.py", line 976, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.local/lib/python3.12/site-packages/icmplib/ping.py", line 130, in ping
    address = resolve(address, family)[0]
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/icmplib/utils.py", line 118, in resolve
    return resolve(name, 6)
           ^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/icmplib/utils.py", line 120, in resolve
    raise NameLookupError(name)
icmplib.exceptions.NameLookupError: The name 'desgkrdhgbfhjd' cannot be resolved

```

</details>
